<?php

/**
 * @file
 * {@inheritdoc}
 */

/**
 * Implements hook_menu().
 */
function deploy_contributions_menu() {
  $items = array();
  $items['admin/config/deploy_contributions'] = array(
    'title' => 'Module Deploy Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_contributions_back_form'),
    'file' => 'includes/deploy_contributions.admin.inc',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
